name = "synthed-website"
compatibility_date = "2023-10-30"

[site]
bucket = "./dist"
entry-point = "."

# Configuration for Cloudflare Pages
pages_build_output_dir = "dist"

[site.static]
include = ["dist"]

# MIME type configurations
[[site.static.mime]]
type = "application/javascript"
patterns = ["**/*.js"]

[[site.static.mime]]
type = "application/javascript"
patterns = ["**/*.module.js"]

[[site.static.mime]]
type = "text/css"
patterns = ["**/*.css"]

# Environment-specific configurations
[env.production]
name = "synthed-website"
