name = "synthed-website"
compatibility_date = "2023-10-30"

[site]
bucket = "./dist"
entry-point = "."

# Configuration for Cloudflare Pages
pages_build_output_dir = "dist"

[site.static]
include = ["dist"]

[env.production]
name = "synthed-website"
